#ifndef __PRINTF_H
#define __PRINTF_H

#undef printf

typedef signed int (*printf_send_func_t)(const unsigned char *, const unsigned int);

/**
 * Sets the function which is used to transmit the 
 * strings generated by printf.
 * */
void printf_setSendFunction(printf_send_func_t function);

int printf(const char *format, ...);

void testprintf();

#endif
